_target_: niceml.dlframeworks.keras.datasets.kerasgenericdataset.KerasGenericDataset
batch_size: 2
datainfo_listing:
  _target_: niceml.data.datainfolistings.semsegdatainfolisting.SemSegDataInfoListing
  location: ${globals.data_location}
data_loader:
  _target_: niceml.data.dataloaders.semseg.semsegdataloader.SemSegDataLoader
target_transformer:
  _target_: niceml.mlcomponents.targettransformer.semsegtargettransformer.SemSegTargetTransformer
input_transformer:
  _target_: niceml.mlcomponents.targettransformer.imageinputtransformer.ImageInputTransformer
shuffle: false
