_target_: niceml.dlframeworks.keras.datasets.kerasdfdataset.KerasDfDataset
id_key: identifier
batch_size: 64
data_location: ${globals.data_location}
subset_name: test
df_filename: numbers_tabular_data_test.parq
