repos:
- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.0.264
  hooks:
    - id: ruff
- repo: https://github.com/PyCQA/bandit
  rev: 1.7.5
  hooks:
  - id: bandit
    exclude: ^tests/
- repo: https://github.com/psf/black
  rev: 23.3.0
  hooks:
  - id: black
- repo: https://github.com/Lucas-C/pre-commit-hooks-safety
  rev: v1.3.1
  hooks:
  - id: python-safety-dependencies-check
    args: ["--ignore=42194,43975,47833,44487,45356,43975,51668"]
    files: pyproject.toml
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-yaml
    types: [yaml]
  - id: check-json
    types: [json]
  - id: check-toml
    types: [toml]
  - id: no-commit-to-branch
    args: ["--branch", "main"]
  - id: end-of-file-fixer
