site_name: niceML
site_url: https://niceml.io/
repo_url: https://github.com/codecentric-oss/niceml
repo_name: codecentric-oss/niceml
edit_uri: edit/main/docs/
theme:
  name: material
  font:
    text: Source Sans Pro
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye
    logo: material/ice-cream
  features:
#    - navigation.tabs
#    - navigation.top
    - navigation.footer
    - navigation.instant
    - navigation.indexes
    - navigation.sections
    - navigation.path
#    - toc.integrate
    - toc.follow
    - search.suggest
    - search.highlight
    - content.tooltips
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.action.edit
    - content.action.view
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: teal
      accent: amber
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: teal
      accent: yellow
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/codecentric-oss/niceml
markdown_extensions:
  - toc:
      permalink: True
  - def_list
  - mdx_include:
      base_path: docs
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.mark
  - attr_list
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            allow_inspection: true
            show_root_heading: true
            show_root_toc_entry: true
            show_root_full_path: false
            show_root_members_full_path: false
            show_category_heading: true
            merge_init_into_class: true
            ignore_init_summary: true
            docstring_section_style: list
            separate_signature: true
  - section-index
  - search
  - table-reader
  - gen-files:
      scripts:
        - docs/jobs/jobsdoc.py
        - docs/jobs/apidocs.py
  - literate-nav:
      implicit_index: true
      nav_file: SUMMARY.md


copyright: |
  &copy; 2023 <a href="https://www.codecentric.de/"  target="_blank" rel="noopener">codecentric AG</a>
