site_name: niceML
site_url: https://niceml.cc/
repo_url: https://github.com/codecentric-oss/niceml
repo_name: codecentric-oss/niceml
edit_uri: edit/main/docs/
theme:
  name: material
  font:
    text: Source Sans Pro
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye
  features:
#    - navigation.tabs
#    - navigation.top
    - navigation.footer
    - navigation.indexes
    - navigation.sections
#    - toc.integrate
    - toc.follow
    - search.suggest
    - search.highlight
    - content.tooltips
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.action.edit
    - content.action.view
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: teal
      accent: amber
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: teal
      accent: yellow
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/codecentric-oss/niceml
markdown_extensions:
  - toc:
      permalink: True
  - def_list
  - mdx_include:
      base_path: docs
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.mark
  - attr_list
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
#  - pymdownx.emoji:
#      emoji_index: !!python/name:materialx.emoji.twemoji
#      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - mkdocstrings  # Use docstrings for documentation
  - search
  - table-reader
  - gen-files:
      scripts:
        - docs/jobsdoc.py

nav:  # Sort the pages
  - index.md
  - Tutorials:
    - Getting Started: tutorials.md
    - Generating Test Data: generate-data.md
  - How-to Guides:
    - How-to-guides: how-to-guides.md
    - Frequently Asked Questions: faq.md
  - Concepts:
    - Use Hydra and Dagster: hydra-dagster.md
    - Use the niceML Dashboard: dashboard.md
  - References:
    - Dagster Jobs: jobsdoc.md

copyright: |
  &copy; 2023 <a href="https://www.codecentric.de/"  target="_blank" rel="noopener">codecentric AG</a>
