FROM python:3.10-buster

WORKDIR /

RUN apt-get update
RUN apt-get install python-opencv -y
RUN pip install -U pip

RUN curl -sSL https://install.python-poetry.org | python -
ENV PATH "/root/.local/bin:${PATH}"

COPY pyproject.toml .
COPY poetry.lock /poetry.lock

# Install extras using poetry
RUN poetry config virtualenvs.create false
{% if EXTRAS %}
RUN poetry install --extras "{{ EXTRAS }}"
{% else %}
RUN poetry install
{% endif %}

# pip install targetwheel.whl

ENV PYTHONPATH "${PYTHONPATH}:."
