# generate numbers sample data
defaults:
  # op for generation of sample data
  - ops/data_generation@ops.data_generation.config: op_data_generation_number.yaml
  # op for splitting data into test, train, validation subset
  - ops/split_data@ops.split_data.config: op_split_data_number.yaml
  # op for cropping numbers from images and store them in a separate folder
  - ops/crop_numbers@ops.crop_numbers.config: op_crop_numbers.yaml
  # op to save images as tabular data
  - ops/image_to_tabular_data@ops.image_to_tabular_data.config: op_image_to_tabular_data.yaml
  # op to normalize tabular data
  - ops/normalization@ops.df_normalization.config: op_norm_numbers_tabular_data.yaml
  # credentials are only used for data location, otherwise ignored
  - /shared/credentials@globals.data_location.credentials: credentials_minio.yaml
  - _self_

globals:
  data_location:
    uri: ${oc.env:DATA_URI,./data}

hydra:
  searchpath:
    - file://configs
