name: Feature Request
description: 🚨 Please make sure to fill out the template carefully. Otherwise, we may not be able to assist you. 🚨
title: "[Feature]: "
labels: ["✨ feature", "📋 needs review"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this feature request. 🚀
  - type: textarea
    id: problem-description
    attributes:
      label: ✏️ Problem Description
      description: Describe the problem or lack of functionality that you want to address. ✨
      placeholder: What is not working as desired? Which feature is missing or could be improved?
    validations:
      required: true
  - type: textarea
    id: feature-request
    attributes:
      label: 💡 Feature Request
      description: What feature do you want to request or improve? 🔍
      placeholder: Please describe the desired feature in detail.
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: 🌍 Context
      description: Describe the context or background in which the new feature or improvement would be useful. 📝
      placeholder: Which user group or target audience would it affect? What benefits would they gain from it?
  - type: textarea
    id: additional-info
    attributes:
      label: 🔍 Additional Information
      description: Include any relevant information that could help the developers better understand the problem and find a solution.
      placeholder:  📷 Screenshots, if possible. 📋 Error logs or error messages. 🕹️ Version of the affected product being used.
  - type: checkboxes
    id: terms
    attributes:
      label: 👍 Code of Conduct
      description: By submitting this feature request, you agree to follow our [Code of Conduct](https://github.com/codecentric-oss/niceml/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
