# evaluate regression experiment with sinus dataframe
defaults:
  - /shared/datasets@ops.prediction.config.datasets.validation: dataset_reg_sinus_test.yaml
  - /shared/datasets@ops.prediction.config.datasets.test: dataset_reg_sinus_test.yaml
  - /shared/datasets@ops.prediction.config.datasets.train_eval: dataset_reg_sinus_test.yaml
  # localize experiment
  - ops/experiment@ops.localize_experiment.config: op_experiment_default.yaml
  # copy existing experiment for evaluation
  - ops/experiment@ops.eval_copy_exp.config: op_experiment_default.yaml
  # experiment locations
  - shared/locations@globals: exp_locations.yaml
  - _self_

hydra:
  searchpath:
    - file://configs

globals:
  exp_name: SampleReg
  exp_prefix: REGSIN

ops:

  localize_experiment:
    config:
      existing_experiment: ${oc.env:EVAL_EXPERIMENT_ID,latest}

  prediction:
    config:
      prediction_handler:
        _target_: niceml.mlcomponents.predictionhandlers.vectorpredictionhandler.VectorPredictionHandler
      model_loader:
        _target_: niceml.dlframeworks.tensorflow.kerasmodelloader.KerasModelLoader
      datasets:
        test:
          set_name: test
          df_loader:
            sample_count: 2000
            seed: 42
        train_eval:
          set_name: train
          df_loader:
            sample_count: 2000
            seed: 12345
        validation:
          set_name: validation
          df_loader:
            sample_count: 2000
            seed: 145

  analysis:
    config:
      result_analyzer:
        _target_: niceml.mlcomponents.resultanalyzers.dataframes.dfanalyzer.DataframeAnalyzer
        metrics:
        - _target_: niceml.mlcomponents.resultanalyzers.dataframes.regmetric.RegMetric
          source_col: ys
          target_col: pred_0000
          function: mse
          function_name: mse
        - _target_: niceml.mlcomponents.resultanalyzers.dataframes.regmetric.RegMetric
          source_col: ys
          target_col: pred_0000
          function: mae
          function_name: mae

  exptests:
    config:
      tests:
        _target_: niceml.experiments.experimenttests.testinitializer.ExpTestProcess
        test_list:
          - _target_: niceml.experiments.experimenttests.validateexps.ModelsSavedExpTest
          - _target_: niceml.experiments.experimenttests.validateexps.ParqFilesNoNoneExpTest
          - _target_: niceml.experiments.experimenttests.validateexps.ExpEmptyTest
          - _target_: niceml.experiments.experimenttests.checkfilesfolderstest.CheckFilesFoldersTest
            folders:
              - configs
            files:
              - configs/train/model_load_custom_objects.yaml
              - configs/train/data_description.yaml
              - train_logs.csv
