globals:
    exp_name: SampleCls
    exp_prefix: CLS
    data_location:
        uri: ${oc.env:DATA_URI,./data}/numbers_cropped_split
datasets:
  data_train: ...
  data_validation: ...
  data_test: ...
train:
  data_description:
    _target_: ...
  model_factory:
    _target_: ...
  learner:
    _target_: ...


prediction:
  prediction_handler: ...
  model_loader: ...
  prediction_function: ...
  prediction_steps: ...

analysis:
  result_analyzer: ...

mlflow: ...
