model_loader:
  _target_: niceml.dlframeworks.tensorflow.kerasmodelloader.KerasModelLoader
prediction_steps: ${niceml.to_int:${oc.env:PREDICTION_STEPS,null}}
prediction_function:
  _target_: niceml.dlframeworks.tensorflow.predictionfunctions.keraspredictionfunction.KerasPredictionFunction
