defaults:
  - /shared/datasets@datasets.validation: dataset_reg_test.yaml
  - /shared/datasets@datasets.test: dataset_reg_test.yaml
  - /shared/datasets@datasets.train_eval: dataset_reg_test.yaml
  - prediction_handler: prediction_handler_vector.yaml
  - op_prediction_base.yaml@_here_
  - _self_

datasets:
  test:
    subset_name: test
  train_eval:
    subset_name: train
  validation:
    subset_name: validation
