# evaluate numbers object detection experiment
defaults:
  # localize experiment
  - ops/experiment@ops.localize_experiment.config: op_experiment_default.yaml
  # copy existing experiment for evaluation
  - ops/experiment@ops.eval_copy_exp.config: op_experiment_default.yaml
  # prediction
  - ops/prediction@ops.prediction.config: op_prediction_objdet.yaml
  # analysis
  - ops/analysis@ops.analysis.config.result_analyzer: op_analysis_objdet.yaml
  # experiment tests
  - ops/exptests@ops.exptests.config.tests: exptests_default.yaml
  # experiment locations
  - shared/locations@globals: exp_locations.yaml
  # resources
  - resources/mlflow@resources.mlflow.config: res_mlflow_base.yaml
  - _self_

hydra:
  searchpath:
    - file://configs

globals:
  exp_name: ObjDet
  exp_prefix: OBJDET
  data_location:
    uri: ${oc.env:DATA_URI,./data}/number_data_split

ops:

  localize_experiment:
    config:
      existing_experiment: ${oc.env:EVAL_EXPERIMENT_ID,latest}
