defaults:
  - /shared/datasets@datasets.validation: dataset_semseg_test.yaml
  - /shared/datasets@datasets.test: dataset_semseg_test.yaml
  - /shared/datasets@datasets.train_eval: dataset_semseg_test.yaml
  - prediction_handler: prediction_handler_semseg.yaml
  - datasets: datasets_generic_default.yaml
  - op_prediction_base.yaml@_here_
  - _self_
