defaults:
  - /shared/datasets@datasets.validation: dataset_objdet_test.yaml
  - /shared/datasets@datasets.test: dataset_objdet_test.yaml
  - /shared/datasets@datasets.train_eval: dataset_objdet_test.yaml
  - prediction_handler: prediction_handler_objdet.yaml
  - datasets: datasets_generic_default.yaml
  - op_prediction_base.yaml@_here_
  - _self_
